name: Issue Report
description: All issues regarding pyloxone
title: "[Bug]: "
labels: ["issue"]
#assignees:
#  - octocat
body:
  - type: markdown
    attributes:
      value: "Please use this template. Otherwise I will close the issue without answering!"
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: A clear and concise description of what the bug is.
      value: ""
    validations:
      required: "true"
  - type: textarea
    id: loxone-version
    attributes:
      label: Firmware of your Miniserver
      description: Which firmware version does your Miniserver use?
      placeholder: Loxone Firmware
      value: ""
    validations:
      required: "true"
  - type: textarea
    id: ha-install-method
    attributes:
      label: HomeAssistant install method
      description: How did you install HomeAssistant? Over Hassio or manual install?
      placeholder: Install method
      value: ""
    validations:
      required: "true"
  - type: textarea
    id: ha-version
    attributes:
      label: Version of HomeAssistant
      description: Which Version do you use of HomeAssistant?
      placeholder: HA Version
      value: ""
    validations:
      required: "true"
  - type: textarea
    id: pyloxone-version
    attributes:
      label: Version of Pyloxone
      description: Which Version of Pyloxone do you use?
      placeholder: Pyloxone Version
      value: ""
    validations:
      required: "true"
  - type: textarea
    id: pyloxone-update
    attributes:
      label: Update pyloxone
      description: Did you try to update pyloxone to the latest version?
      placeholder: Pyloxone update
      value: ""
    validations:
      required: "true"
  - type: textarea
    id: pyloxone-log
    attributes:
      label: Log
      description: Paste the error log with the following settings
      placeholder: Pyloxone update
      value: "logger:
                default: warning
                logs:
                  homeassistant: warning
                  homeassistant.helpers: warning
                  custom_components.loxone: debug
                  custom_components.loxone.api: debug"
    validations:
      required: "false"



#  - type: textarea
#    id: logs
#    attributes:
#      label: Relevant log output
#      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
#      render: shell

#  - type: dropdown
#    id: version
#    attributes:
#      label: Version
#      description: What version of our software are you running?
#      options:
#        - 1.0.2 (Default)
#        - 1.0.3 (Edge)
#      default: 0
#    validations:
#      required: true
#  - type: dropdown
#    id: browsers
#    attributes:
#      label: What browsers are you seeing the problem on?
#      multiple: true
#      options:
#        - Firefox
#        - Chrome
#        - Safari
#        - Microsoft Edge
#  - type: textarea
#    id: logs
#    attributes:
#      label: Relevant log output
#      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
#      render: shell
#  - type: checkboxes
#    id: terms
#    attributes:
#      label: Code of Conduct
#      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
#      options:
#        - label: I agree to follow this project's Code of Conduct
#          required: true
